version: "3.8"

networks:
  ipfs:
    ipam:
      config:
        - subnet: 172.20.0.0/24
services:
  ipfs:
    container_name: ipfs
    build:
      context: .
      dockerfile: ipfs/Dockerfile
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
    volumes:
      - ./compose/ipfs:/data/ipfs
    networks:
      ipfs:
        ipv4_address: 172.20.0.6

  ipfs-cluster:
    container_name: ipfs-cluster
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs
    links:
      - ipfs 
    environment:
      CLUSTER_IPFSPROXY_NODEMULTIADDRESS: /ip4/172.20.0.6/tcp/5001
      CLUSTER_PEERNAME: ipfs-cluster
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094
      CLUSTER_MONITORPINGINTERVAL: 2s

    ports:
      - "127.0.0.1:9094:9094"
      - "9095:9095"
      - "9096:9096"
    volumes:
      - ./compose/ipfs-cluster:/data/ipfs-cluster
    networks:
      ipfs:
        ipv4_address: 172.20.0.7


  zeitgeist-blockchain:
    container_name: zeitgeist-node
    image: zeitgeistpm/zeitgeist-node:latest
    # Docker container user "zeitgeist" has insufficient permissions
    user: root
    ports:
      - ${ZTG_CHAIN_PORT}:30333
      - ${ZTG_CHAIN_RPC_PORT}:9933
      - ${ZTG_CHAIN_WS_PORT}:9944
    volumes:
      - ${BASE_PATH}:/zeitgeist/data
    command: --base-path=/zeitgeist/data --dev --ws-external --rpc-external --rpc-cors all --rpc-methods Unsafe

  # zeitgeist-frontend:
    # todo

  # zeitgeist-subsquid:
    # todo
