version: "3.8"

networks:
  blockchain:
  frontend:
  ipfs:
  subsquid:

services:
  autoheal:
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  ipfs:
    container_name: ipfs
    build:
      context: .
      dockerfile: ipfs/Dockerfile
    ports:
      - ${IPFS_SWARM_PORT}:4001
      - ${IPFS_API_PORT}:5001
      - ${IPFS_GATEWAY_PORT}:8080
    networks:
      - ipfs
    volumes:
      - ${BASE_PATH}/ipfs:/data/ipfs
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5001/webui || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  zeitgeist-blockchain:
    container_name: zeitgeist-node
    image: zeitgeistpm/zeitgeist-node:latest
    # Docker container user "zeitgeist" has insufficient permissions
    user: root
    ports:
      - ${ZTG_CHAIN_PORT}:30333
      - ${ZTG_CHAIN_RPC_PORT}:9933
      - ${ZTG_CHAIN_WS_PORT}:9944
    networks:
      - blockchain
    volumes:
      - ${BASE_PATH}:/zeitgeist/data
    command: --base-path=/zeitgeist/data --dev --ws-external --rpc-external --rpc-cors all --rpc-methods Unsafe

#  zeitgeist-frontend:
#    networks:
#      - blockchain
#      - frontend
#      - ipfs
#      - subsquid
#  zeitgeist-subsquid:
#    networks:
#      - blockchain
#      - ipfs
#      - subsquid
