version: "3.8"

networks:
  blockchain:
  frontend:
  ipfs:
  subsquid:


services:
  autoheal:
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  ipfs:
    container_name: ipfs
    build:
      context: .
      dockerfile: ipfs/Dockerfile
    ports:
      - ${IPFS_SWARM_PORT}:4001
      - ${IPFS_API_PORT}:5001
      - ${IPFS_GATEWAY_PORT}:8080
    networks:
      - ipfs
    volumes:
      - ${BASE_PATH}/ipfs:/data/ipfs
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5001/webui || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  zeitgeist-blockchain:
    container_name: zeitgeist-node
    image: zeitgeistpm/zeitgeist-node:latest
    # Docker container user "zeitgeist" has insufficient permissions
    user: root
    ports:
      - ${ZTG_CHAIN_PORT}:30333
      - ${ZTG_CHAIN_RPC_PORT}:9933
      - ${ZTG_CHAIN_WS_PORT}:9944
    networks:
      - blockchain
    volumes:
      - ${BASE_PATH}:/zeitgeist/data
    command: --base-path=/zeitgeist/data --dev --ws-external --rpc-external --rpc-cors all --rpc-methods Unsafe

  indexer-db:
    container_name: indexer-db
    image: cockroachdb/cockroach:v22.2.2
    ports:
      - ${INDEXER_DB_PORT}:26257
    networks:
      - subsquid
    volumes:
      - ${BASE_PATH}:/cockroach/cockroach-data
    command: start-single-node --insecure

  indexer:
    container_name: indexer
    image: subsquid/substrate-ingest:1
    restart: unless-stopped
    depends_on:
      - zeitgeist-blockchain
      - indexer-db
    networks:
      - blockchain
      - subsquid
    ports:
      - ${INDEXER_PROM_PORT}:9090
    command: -e ws://zeitgeist-node:${ZTG_CHAIN_WS_PORT} -c 5 --out postgres://root@indexer-db:${INDEXER_DB_PORT}/defaultdb

  indexer-api:
    container_name: indexer-api
    image: subsquid/substrate-gateway:2.5.0
    depends_on:
      - indexer
    networks:
      - subsquid
    environment:
      RUST_LOG: "actix_web=info,actix_server=info"
    ports:
      - ${INDEXER_API_PORT}:8000
    command: --database-url postgres://root@indexer-db:${INDEXER_DB_PORT}/defaultdb --database-max-connections 10

  processor-db:
    container_name: processor-db
    image: postgres:14
    networks:
      - subsquid
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - ${PROCESSOR_DB_PORT}:5432

  processor:
    container_name: processor
    image: zeitgeistpm/squid-processor:latest
    depends_on:
      - indexer-api
      - processor-db
      - ipfs
    networks:
      - subsquid
    environment:
      NODE_ENV: local
      PROJECT_NAME: zeitgeist-squid
      WS_NODE_URL: ws://zeitgeist-node:9944
      DB_HOST: processor-db
      DB_NAME: postgres
      DB_PORT: ${PROCESSOR_DB_PORT}
      BATCH_SIZE: 100
      INDEXER_ENDPOINT_URL: http://host.docker.internal:${INDEXER_API_PORT}/graphql
      PROCESSOR_PROMETHEUS_PORT: ${PROCESSOR_PROM_PORT}
    ports:
      - ${PROCESSOR_PROM_PORT}:9090

  processor-api:
    container_name: processor-api
    image: zeitgeistpm/squid-processor:latest
    depends_on:
      - processor
    networks:
      - subsquid
    environment:
      DB_HOST: processor-db
      DB_NAME: postgres
      DB_PORT: ${PROCESSOR_DB_PORT}
      GQL_PORT: ${PROCESSOR_API_PORT}
    ports:
      - ${PROCESSOR_API_PORT}:4350
    command: yarn api:start

#  zeitgeist-frontend:
#    networks:
#      - blockchain
#      - frontend
#      - ipfs
#      - subsquid
